### ISSUE TITLE
tag releases

### ISSUE THREAD

**Issue by johnnybubonic** [danderson/netboot#102]
Please use git tags to version releases.

**Comment by prologic** [comment]
Yes please tag and release a new version

**Comment by prologic** [comment]
Please also consider publishing binaries to Github releases.

You can borrow [tools/release.sh](https://github.com/prologic/ed/blob/master/tools/release.sh) and sue use [GoReleaser](https://goreleaser.com/) and borrow one of my configs from say [.goreleaser.yml](https://github.com/prologic/ed/blob/master/.goreleaser.yml)

**Comment by danderson** [comment]
There's never been a release of this code. Given that I haven't developed it for years, I don't really see a reason to start now. It's a tool I use because I find it useful, and in that use `go get` is plenty enough.
