### ISSUE TITLE
enable docker hub autobuild and update docker image(s)

### ISSUE THREAD

**Issue by realtime-neil** [danderson/netboot#115]
The registry here...

    https://hub.docker.com/r/danderson/pixiecore

...hasn't been updated in a long time. Additionally, it would be nice if "autobuild" were enabled so that every commit to the github remote triggered a fresh build on the docker hub.

**Comment by danderson** [comment]
The current image is https://hub.docker.com/repository/docker/pixiecore/pixiecore , i.e. in the pixiecore organization. That one gets updated on every push, IIRC (last updated 2h ago).

**Comment by realtime-neil** [comment]
Whoops, my bad; please close at your leisure.
