### ISSUE TITLE
Arch Linux quick command needs cms_verify=y

### ISSUE THREAD

**Issue by topcat001** [danderson/netboot#137]
Hi, in https://github.com/danderson/netboot/blob/0e2ca55deb5097ab9a22f35378b378d228fff701/pixiecore/cli/quickcmd.go#L335 `verify=y` is no longer supported, which causes an error. We need to change this to `cms_verify=y`. Please also see https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio-archiso/-/issues/16. Thank you!

**Comment by icanwalkonwater** [comment]
This if fixed by #139
