### ISSUE TITLE
Deploy an ARMv6 Build

### ISSUE THREAD

**Issue by DavidJFelix** [danderson/netboot#36]
I'm using a raspberrypi to run pixiecore and everything compiles great, but it would be nice if installing from .deb was possible so that I don't also need go. The travis-ci runners support cross architecture compilation, so it should be possible to specify arch in the build matrix there with little extra effort.

**Comment by danderson** [comment]
That should be feasible. I'll need to rework the Travis configuration to use the new build stages feature, right now it's a big mess designed to work around the lack of stages. I'll see if I can add an ARMv6 build at the same time.

**Comment by DavidJFelix** [comment]
@danderson I don't think you need to do all that. Just use travis' build matrix to set `GOARCH` to arm. That would cover the go portion of the code. I'm not sure if there are added complications around cross compiling non-go. Let me investigate.

**Comment by danderson** [comment]
From your request, I'm assuming you also want me to push a Debian package to packagecloud.io, so you can install it directly? Adding ARM to the build matrix is easy, the slightly harder parts are getting tests to either pass or be skipped, build more than just an x86_64 package, and handle the deploy correctly.

To be clear, none of that is especially difficult, it just requires changing the Travis config around a bunch :)

**Comment by danderson** [comment]
Phew, okay. After a lot of struggling with Travis, the build now looks like this: https://travis-ci.org/google/netboot

In the test stage, both amd64 and ARMv6 binaries are compiled (to find any arch-specific build failures), and the amd64 unit tests are run (cannot run arm, no support on travis).

In the deploy stage, we build both amd64 and armhf (aka ARMv6) packages and push them to packagecloud.

@DavidJFelix Can you try using the Debian packages at https://packagecloud.io/danderson/pixiecore to install on your RPi? I think I got the target right, based on what the internet tells me about the architecture of an RPi, but it'd be good to have confirmation :)

**Comment by DavidJFelix** [comment]
Awesome. Thanks @danderson. I'll verify it when I'm back at work.

**Comment by danderson** [comment]
Well, I don't know if it worked or not, but my Packagecloud account blew through its bandwidth quota, so the repository is disabled now :(

I'll have to figure something out after work. In the meantime, if you'd like a .deb package for rpi, I can upload it somewhere for you to manually install, while I get a repository up and kicking.

**Comment by DavidJFelix** [comment]
I haven't gotten the chance to test it. No hurries though, I'm still just using the go-get version until I have time to re-provision the pi.

**Comment by DavidJFelix** [comment]
Just out of curiosity (I was looking into packagecloud out of interest), how did you blow through the bandwidth quota? It doesn't seem like that would use very much.

**Comment by danderson** [comment]
The blowout was actually caused by another package I keep there. I stupidly set it up to be unconditionally rebuilt every 24h, and it's installed by a dozen machines. 12 machines refetching 5MB every day means I blew the free 250M quota in just under 4 days :)

**Comment by DavidJFelix** [comment]
I'm going to close to clean up my own github space a bit. If you decide to pursue it, feel free to reopen.
