### ISSUE TITLE
[DHCP] unsupported client firmware type '16'

### ISSUE THREAD

**Issue by albttx** [danderson/netboot#72]
```
pixiecore_1  | [DHCP] Unusable packet from xx:xx:xx:xx:xx:xx: unsupported client firmware type '16' (please file a bug!)
```

The server is a baremetal in UEFI

Does anyone have the same firmware issue ?

**Comment by danderson** [comment]
That's the architecture code for arm64. Pixiecore only boots x86 machines.

It would be nice to support other architectures, but this project is not under active development.
