### ISSUE TITLE
Fix the image builder

### ISSUE THREAD

**Issue by danderson** [danderson/netboot#78]
The image builder still depends on Glide, but I switched to Go modules. Oops. Need to fix that.

**Comment by ccollicutt** [comment]
Just FYI I tried to build the docker image today, obviously failed. :) But just wanted to let you know I did try to use it. Thanks for the software. :)

**Comment by realtime-neil** [comment]
@danderson can this issue be closed now that the dockerfile is working?

**Comment by danderson** [comment]
Sure.
