### ISSUE TITLE
Booting Windows PE fails

### ISSUE THREAD

**Issue by mapl** [danderson/netboot#92]
Trying to use wimboot with netboot, but without success.

ref.: http://ipxe.org/wimboot

my cmd: 

sudo go/bin/pixiecore boot ipxeboot/wimboot ipxeboot/macrium/Boot/BCD ipxeboot/macrium/Boot/boot.sdi ..

Result in VMware Workstation:
.
.
.

**wimboot v.2.6.0 --....
**command line: "initrd=initrd0 initrd=initrd1"
Unrecognized argument "initrd=initrd1"****

Press a key to reboot

**Comment by danderson** [comment]
`pixiecore boot` only works for booting linux kernels and ramdisks. Wimboot doesn't accept the same parameters as a linux kernel, so yeah, it won't work.
