### ISSUE TITLE
pixiecore: UI is deprecated?

### ISSUE THREAD

**Issue by antoinerg** [danderson/netboot#97]
I tried running the Docker image for `pixiecore` but couldn't get the UI to show up. I am under the impression that it is deprecated considering `netboot/pixiecore/ui/` does not exist on `master`. Is that really the case?

**Comment by antoinerg** [comment]
Ok, I found out it was removed in https://github.com/danderson/netboot/commit/6cd17867fcfc01351c565f6ab9294d156cf82776

Might be useful to update the README to reflect that.

**Comment by prologic** [comment]
I see no mention of a UI anywhere on the README. Maybe we can close this now?

**Comment by danderson** [comment]
Yeah, it was removed. Wasn't as useful as I thought it would be.
